create table "users"(
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(20) not null,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);






