create table ticket(
    id bigint generated by default as identity primary key,
    title varchar(100) not null,
    description varchar(255) not null,
    status varchar(20) not null,
    priority varchar(20) not null,
    user_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,

    foreign key (user_id) references users(id)
);
