create table comment(
    id bigint generated by default as identity primary key,
    message varchar(255) not null,
    ticket_id bigint not null,
    user_id bigint not null,
    created_at timestamp not null,
    foreign key (ticket_id) references ticket(id),
    foreign key (user_id) references users(id)

)