create table notification(
    id bigint generated by default as identity primary key,
    title varchar(100) not null,
    message varchar(255) not null,
    created_at timestamp not null default current_timestamp,
    is_read boolean not null default false,
    user_id bigint not null,
    foreign key (user_id) references users(id)
)